"""Render benchmark tables from completed runs; no figure here is typed by hand.

    python -m vigil.bench report --data lanl

Reads `runs/*/metrics.json` for one dataset and writes `docs/BENCHMARKS.md`
and `models/benchmarks.json`. Runs of the same experiment and parameters
with different seeds are grouped: the table shows the mean, the spread across
seeds, and the bootstrap interval of the first seed.
"""

from __future__ import annotations

import json
import statistics
from collections import defaultdict
from pathlib import Path

import yaml

from ..data.lanl import REPO
from .runner import RUNS

COLUMNS = [("ap", "AP"), ("roc_auc", "ROC-AUC"), ("recall@50/day", "Recall @50/day"),
           ("recall@100/day", "Recall @100/day"), ("recall@500/day", "Recall @500/day"),
           ("tpr@fpr=0.0001", "TPR @FPR 1e-4")]
PUBLISHED = REPO / "configs" / "published_baselines.yaml"


def collect(data: str, runs_dir: Path = RUNS) -> dict:
    groups: dict[tuple, list] = defaultdict(list)
    for m in sorted(runs_dir.glob("*/metrics.json")):
        cfg = yaml.safe_load((m.parent / "config.yaml").read_text())
        if cfg["name"] != data:
            continue
        key = (cfg["experiment"], json.dumps(cfg["params"], sort_keys=True))
        groups[key].append({"run": m.parent.name, "seed": cfg["seed"], "splits": cfg["data"]["splits"],
                            "metrics": json.loads(m.read_text()),
                            "meta": json.loads((m.parent / "meta.json").read_text())})
    out = {"data": data, "experiments": []}
    for (exp, params), runs in sorted(groups.items()):
        runs.sort(key=lambda r: r["seed"])
        entry = {"experiment": exp, "params": json.loads(params), "seeds": [r["seed"] for r in runs],
                 "supervised": bool(runs[0]["meta"].get("supervised")),
                 "runs": [r["run"] for r in runs], "splits": {}}
        for split in runs[0]["metrics"]:
            first = runs[0]["metrics"][split]
            s = {"n_positive": first["n_positive"], "events_scored": first["events_scored"],
                 "days": first["days"], "metrics": {}}
            for k, cell in first["metrics"].items():
                vals = [r["metrics"][split]["metrics"][k]["value"] for r in runs if split in r["metrics"]]
                s["metrics"][k] = {"mean": statistics.fmean(vals),
                                   "std": statistics.stdev(vals) if len(vals) > 1 else None,
                                   "lo": cell.get("lo"), "hi": cell.get("hi")}
            entry["splits"][split] = s
        out["experiments"].append(entry)
    out["published"] = (yaml.safe_load(PUBLISHED.read_text()) or []) if PUBLISHED.exists() else []
    return out


def _fmt(v: float) -> str:
    """Three decimals normally, two significant digits for very small values.

    Average precision against a 1-in-276,000 positive rate lives around 1e-4, and
    printing that as "0.000" hides the entire result.
    """
    if v != v:  # NaN
        return "n/a"
    if v == 0:
        return "0"
    return f"{v:.3f}" if abs(v) >= 0.005 else f"{v:.1e}"


def _cell(m: dict) -> str:
    if m["mean"] != m["mean"]:  # NaN
        return "n/a"
    txt = _fmt(m["mean"])
    if m["std"] is not None:
        txt += f" ± {_fmt(m['std'])}"
    if m["lo"] is not None:
        txt += f" <sub>[{_fmt(m['lo'])}, {_fmt(m['hi'])}]</sub>"
    return txt


def render(bench: dict) -> str:
    L = [f"# Benchmarks: {bench['data']}", "",
         "Generated by `python -m vigil.bench report` from `runs/*/metrics.json`. Do not edit by hand.", "",
         "Values are point estimates on the split; brackets are 95% bootstrap intervals resampled over users; "
         "`±` is the standard deviation across seeds when a model was run with several. ROC-AUC is inflated "
         "when positives are this rare, so read AP and the alert-budget recall first.", ""]
    splits = sorted({s for e in bench["experiments"] for s in e["splits"]}, key=lambda s: (s != "test", s))
    for split in splits:
        rows = [e for e in bench["experiments"] if split in e["splits"]]
        ref = rows[0]["splits"][split]
        L += [f"## {split} (days {ref['days'][0]}–{ref['days'][1] - 1}, {ref['n_positive']} red-team events)", "",
              "| model | seeds | " + " | ".join(c for _, c in COLUMNS) + " |",
              "|---|---:|" + "---:|" * len(COLUMNS)]
        rows.sort(key=lambda e: -e["splits"][split]["metrics"]["ap"]["mean"])
        for e in rows:
            name = e["experiment"] + (" †" if e["supervised"] else "")
            name += f" `{json.dumps(e['params'])}`" if e["params"] else ""
            cells = [_cell(e["splits"][split]["metrics"][k]) for k, _ in COLUMNS]
            L.append(f"| {name} | {len(e['seeds'])} | " + " | ".join(cells) + " |")
        L.append("")
    if any(e["supervised"] for e in bench["experiments"]):
        L += ["† Supervised: trained on red-team labels from the training window. This is an upper bound; a "
              "deployment facing a new intrusion has no such labels.", ""]
    L += ["## Published results on LANL", ""]
    if bench["published"]:
        L += ["Protocols differ between papers and from this benchmark; each row notes how. These are context, "
              "not head-to-head comparisons.", "", "| work | metric | value | protocol notes |", "|---|---|---:|---|"]
        L += [f"| {p['work']} | {p['metric']} | {p['value']} | {p['notes']} |" for p in bench["published"]]
    else:
        L.append("Not added yet: figures go in `configs/published_baselines.yaml` only after checking them "
                 "against the papers.")
    return "\n".join(L) + "\n"


README_START = "<!-- LANL:START -->"
README_END = "<!-- LANL:END -->"
HEADLINE = [("ap", "AP"), ("recall@100/day", "Recall @100 alerts/day"), ("roc_auc", "ROC-AUC")]


def render_readme(bench: dict, split: str = "test") -> str:
    """The short headline table for the README, generated so it cannot drift from the runs."""
    rows = [e for e in bench["experiments"] if split in e["splits"]]
    if not rows:
        return "No completed runs yet."
    ref = rows[0]["splits"][split]
    rows.sort(key=lambda e: -e["splits"][split]["metrics"]["ap"]["mean"])
    L = [f"Test window: days {ref['days'][0]}–{ref['days'][1] - 1}, "
         f"{ref['n_positive']} labelled red-team logons among {ref['events_scored']:,} scored authentications "
         f"(about 1 in {ref['events_scored'] // max(ref['n_positive'], 1):,}, so a random scorer lands near "
         f"AP {ref['n_positive'] / ref['events_scored']:.1e}).", "",
         "| Model | " + " | ".join(c for _, c in HEADLINE) + " |", "|---|---:|---:|---:|"]
    for e in rows:
        name = e["experiment"] + (" †" if e["supervised"] else "")
        L.append(f"| {name} | " + " | ".join(_cell(e["splits"][split]["metrics"][k]) for k, _ in HEADLINE) + " |")
    L += ["", "Brackets are 95% bootstrap intervals over users. ROC-AUC is reported because published work does, but "
              "at this class imbalance it flatters everything: read AP and the alert-budget recall.",
          "", f"Full tables, ablations and published-baseline comparisons: [`docs/BENCHMARKS.md`](docs/BENCHMARKS.md)."]
    if any(e["supervised"] for e in rows):
        L += ["", "† Trained on red-team labels from an earlier window: an upper bound, not a deployable result."]
    return "\n".join(L)


def update_readme(bench: dict, readme: Path | None = None) -> bool:
    readme = readme or REPO / "README.md"
    text = readme.read_text(encoding="utf-8")
    if README_START not in text or README_END not in text:
        return False
    head, rest = text.split(README_START, 1)
    _, tail = rest.split(README_END, 1)
    readme.write_text(f"{head}{README_START}\n{render_readme(bench)}\n{README_END}{tail}", encoding="utf-8")
    return True


def write(data: str, runs_dir: Path = RUNS, docs: Path | None = None, out_json: Path | None = None) -> dict:
    bench = collect(data, runs_dir)
    if data == "lanl":  # the published benchmark; anything else (the fixture) stays under runs/
        docs = docs or REPO / "docs" / "BENCHMARKS.md"
        out_json = out_json or REPO / "models" / "benchmarks.json"
    else:
        docs = docs or runs_dir / f"BENCHMARKS-{data}.md"
        out_json = out_json or runs_dir / f"benchmarks-{data}.json"
    docs.parent.mkdir(parents=True, exist_ok=True)
    out_json.parent.mkdir(parents=True, exist_ok=True)
    docs.write_text(render(bench), encoding="utf-8")
    out_json.write_text(json.dumps(bench, indent=1))
    if data == "lanl":
        update_readme(bench)
    return bench
