"""Render benchmark tables from completed runs; no figure here is typed by hand.

    python -m vigil.bench report --data lanl

Reads `runs/*/metrics.json` for one dataset and writes `docs/BENCHMARKS.md`
and `models/benchmarks.json`. Runs of the same experiment and parameters
with different seeds are grouped: the table shows the mean, the spread across
seeds, and the bootstrap interval of the first seed.
"""

from __future__ import annotations

import json
import statistics
from collections import defaultdict
from pathlib import Path

import yaml

from ..data.lanl import REPO
from .runner import RUNS

COLUMNS = [("ap", "AP"), ("roc_auc", "ROC-AUC"), ("recall@50/day", "Recall @50/day"),
           ("recall@100/day", "Recall @100/day"), ("recall@500/day", "Recall @500/day"),
           ("tpr@fpr=0.0001", "TPR @FPR 1e-4")]
PUBLISHED = REPO / "configs" / "published_baselines.yaml"


def collect(data: str, runs_dir: Path = RUNS) -> dict:
    groups: dict[tuple, list] = defaultdict(list)
    for m in sorted(runs_dir.glob("*/metrics.json")):
        cfg = yaml.safe_load((m.parent / "config.yaml").read_text())
        if cfg["name"] != data:
            continue
        key = (cfg["experiment"], json.dumps(cfg["params"], sort_keys=True))
        groups[key].append({"run": m.parent.name, "seed": cfg["seed"], "splits": cfg["data"]["splits"],
                            "metrics": json.loads(m.read_text()),
                            "meta": json.loads((m.parent / "meta.json").read_text())})
    out = {"data": data, "experiments": []}
    for (exp, params), runs in sorted(groups.items()):
        runs.sort(key=lambda r: r["seed"])
        entry = {"experiment": exp, "params": json.loads(params), "seeds": [r["seed"] for r in runs],
                 "runs": [r["run"] for r in runs], "splits": {}}
        for split in runs[0]["metrics"]:
            first = runs[0]["metrics"][split]
            s = {"n_positive": first["n_positive"], "events_scored": first["events_scored"],
                 "days": first["days"], "metrics": {}}
            for k, cell in first["metrics"].items():
                vals = [r["metrics"][split]["metrics"][k]["value"] for r in runs if split in r["metrics"]]
                s["metrics"][k] = {"mean": statistics.fmean(vals),
                                   "std": statistics.stdev(vals) if len(vals) > 1 else None,
                                   "lo": cell.get("lo"), "hi": cell.get("hi")}
            entry["splits"][split] = s
        out["experiments"].append(entry)
    out["published"] = (yaml.safe_load(PUBLISHED.read_text()) or []) if PUBLISHED.exists() else []
    return out


def _cell(m: dict) -> str:
    if m["mean"] != m["mean"]:  # NaN
        return "n/a"
    txt = f"{m['mean']:.3f}"
    if m["std"] is not None:
        txt += f" ± {m['std']:.3f}"
    if m["lo"] is not None:
        txt += f" <sub>[{m['lo']:.3f}, {m['hi']:.3f}]</sub>"
    return txt


def render(bench: dict) -> str:
    L = [f"# Benchmarks: {bench['data']}", "",
         "Generated by `python -m vigil.bench report` from `runs/*/metrics.json`. Do not edit by hand.", "",
         "Values are point estimates on the split; brackets are 95% bootstrap intervals resampled over users; "
         "`±` is the standard deviation across seeds when a model was run with several. ROC-AUC is inflated "
         "when positives are this rare, so read AP and the alert-budget recall first.", ""]
    splits = sorted({s for e in bench["experiments"] for s in e["splits"]}, key=lambda s: (s != "test", s))
    for split in splits:
        rows = [e for e in bench["experiments"] if split in e["splits"]]
        ref = rows[0]["splits"][split]
        L += [f"## {split} (days {ref['days'][0]}–{ref['days'][1] - 1}, {ref['n_positive']} red-team events)", "",
              "| model | seeds | " + " | ".join(c for _, c in COLUMNS) + " |",
              "|---|---:|" + "---:|" * len(COLUMNS)]
        rows.sort(key=lambda e: -e["splits"][split]["metrics"]["ap"]["mean"])
        for e in rows:
            name = e["experiment"] + (f" `{json.dumps(e['params'])}`" if e["params"] else "")
            cells = [_cell(e["splits"][split]["metrics"][k]) for k, _ in COLUMNS]
            L.append(f"| {name} | {len(e['seeds'])} | " + " | ".join(cells) + " |")
        L.append("")
    L += ["## Published results on LANL", ""]
    if bench["published"]:
        L += ["Protocols differ between papers and from this benchmark; each row notes how. These are context, "
              "not head-to-head comparisons.", "", "| work | metric | value | protocol notes |", "|---|---|---:|---|"]
        L += [f"| {p['work']} | {p['metric']} | {p['value']} | {p['notes']} |" for p in bench["published"]]
    else:
        L.append("Not added yet: figures go in `configs/published_baselines.yaml` only after checking them "
                 "against the papers.")
    return "\n".join(L) + "\n"


def write(data: str, runs_dir: Path = RUNS, docs: Path | None = None, out_json: Path | None = None) -> dict:
    bench = collect(data, runs_dir)
    if data == "lanl":  # the published benchmark; anything else (the fixture) stays under runs/
        docs = docs or REPO / "docs" / "BENCHMARKS.md"
        out_json = out_json or REPO / "models" / "benchmarks.json"
    else:
        docs = docs or runs_dir / f"BENCHMARKS-{data}.md"
        out_json = out_json or runs_dir / f"benchmarks-{data}.json"
    docs.parent.mkdir(parents=True, exist_ok=True)
    out_json.parent.mkdir(parents=True, exist_ok=True)
    docs.write_text(render(bench), encoding="utf-8")
    out_json.write_text(json.dumps(bench, indent=1))
    return bench
